name: 'Android build Action'
description: 'Build & execute android gradle tasks'
author: 'Dionysis Lorentzos (Diolor)'
inputs: 
  gradle-command:
    description: 'Gradle commands. E.g: clean assebleDebug'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gradle-command }}
